version: '3.7'

services:

  db:
#    container_name: database
    image: mariadb:10.2.12
    restart: always
    ports:
      - 3306:3306
    environment:
      TZ : Asia/Seoul
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
#    networks:
#      - backend-network

    volumes:
      #- ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

#  application:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: always
#    ports:
#    - 8088:8088
#    depends_on:
#      - database
#    environment:
#      TZ : Asia/Seoul
#      SPRING_PROFILES_ACTIVE : local
#      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/zzaisang_local?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&tinyInt1isBit=false
#      SPRING_DATASOURCE_USERNAME: local
#      SPRING_DATASOURCE_PASSWORD: zaq1234!
#    networks:
#      - backend-network

#networks:
#  backend-network: